// <auto-generated />
namespace M17E_Caderneta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fotoPerfil : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fotoPerfil));
        
        string IMigrationMetadata.Id
        {
            get { return "202104210942093_fotoPerfil"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
